baseURL = "https://100r.netlify.app"
disableLanguages = ["de"]
disqusShortname = "100rueng"
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "20"
theme = "geeky-pro888"
title = "Geeky | Hugo Personal Blog Template"
[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"
[imaging]
quality = 90
[markup.goldmark.renderer]
unsafe = true
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]
[module.hugoVersion]
extended = true
min = "0.87.0"
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]
