about_widget_content = "Lorem ipsum dolor sit amet, conse tfctetur adipiscing elit. Vel in in donec iaculis tempasus odio nunc laoreet . Libero ullam rgscorper."
address = "9567 Turner Trace Apt. BC C3G8A4"
author = "PNCKDEVAPP"
contact_form_action = "#"
copyright = "Designed By [PNCKDEVAPP](https://pnckdevapp.com/)"
custom_script = ""
description = "This is meta description"
email = "info@email.com"
favicon = "images/favicon.png"
featured_post_title = "Featured Post"
footer_content = "Lorem ipsum dolor sit amt, conse adip iscing. donec iaculis tempasus laoreet. Libero ullam rgscper."
image = "images/logo.png"
logo = "images/logo.png"
logo_text = "Boilerplate"
logo_width = "150x"
mainSections = ["blog"]
mobile = "+211234565523"
navbar_fixed = false
recent_post_title = "Recent Post"
search = true
[advertisement]
image = "images/promotion.png"
link = "https://gethugothemes.com/"
[banner]
background_image = "/images/banner-bg-shape.svg"
button_label = "Know About Me"
button_link = "about/"
content = "Are Developer and recently started your own business Already made website to ensure presence wants to develop."
enable = true
image = "images/banner.png"
title_large = "Welcome **!**"
title_small = "to Jhon Bravo Blog"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[preloader]
enable = false
preloader = ""
[subscription]
enable = false
mailchimp_form_action = ""
mailchimp_form_name = ""
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
[[social]]
icon = "fab fa-facebook"
link = "#"
title = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "#"
title = "twitter"
[[social]]
icon = "fab fa-instagram"
link = "#"
title = "instagram"
[[social]]
icon = "fab fa-linkedin"
link = "#"
title = "linkedin"
